// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xadldmfdzafuocpixbxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhZGxkbWZkemFmdW9jcGl4YnhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjkwNDUsImV4cCI6MjA2NzU0NTA0NX0.cNzzSA06EeSUrqjVU0WuEGV6-eel_2FNtuDnuOUkHoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});